server {
   listen *:80 default_server;

   server_name "jenkins";

   location ~ /static/[0-9a-z]\{8\} {
      proxy_pass http://jenkins:8080;
   }

   location / {
      proxy_pass http://jenkins:8080;

      proxy_set_header          Host $host:$server_port;
      proxy_set_header          X-Real_IP $remote_addr;
      proxy_set_header          X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header          X-Forwarded-Proto $scheme;

      proxy_read_timeout        90;
   }
}